### ISSUE TITLE
Circular dependency problem?

### ISSUE THREAD

**Issue by egils-consulting** [AstroCB/Messenger-CLI#18]
Got this error after npm install finished without errors.
```
npm start

> Messenger-CLI@1.0.0 start /home/egil/src/js/messenger-cli
> node index.js

What's your Facebook email? (node:141406) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```
The trace is here:
```
node --trace-warnings index.js
What's your Facebook email? (node:141445) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:853:11)
    at Object.get (internal/modules/cjs/loader.js:867:5)
    at Object.exports.setLevels (/home/egil/src/js/messenger-cli/node_modules/winston/lib/winston/common.js:35:14)
    at Object.<anonymous> (/home/egil/src/js/messenger-cli/node_modules/winston/lib/winston.js:84:8)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/egil/src/js/messenger-cli/node_modules/prompt/lib/prompt.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
```

**Comment by AstroCB** [comment]
Hmm, can't seem to replicate this error.
